version: '3'

services:
    web-node-js:
        image: moomark/nodejs:latest
        ports:
            - "3000:3000"
        environment:
            - MONGODB_ADDON_URI=mongodb://mongodb:27017/test
    mongodb:
        image: mongo:4.1
        ports: 
            - "27017:27017"
        
